### ISSUE TITLE
Add support for Asset Renditions and their referencing

### ISSUE THREAD

**Issue by Suzii** [Kentico/kontent-management-sdk-net#137]
### Motivation

Asset Renditions were added to Kontent App a while ago. They can be referenced from the Asset element in order to customize images. Now the feature has made its way to MAPI as well, and we should add support for managing renditions and referencing them to SDK as well.

### Proposed solution

- Models and endpoints for CRUD operations for Asset rendition entity (`/asset/{assetId}/renditions/{renditionId}`)
- Extending the current value of AssetElement with renditions property (`IEnumerable<References>` -> `IEnumerable<AssetReferencesWithRenditions>`. To give you an idea, this is the Before and After state of the Asset element in `v2/variant` endpoint:

BEFORE
```
{
  element = "",
  value = [
    { id = "" },
    { codename = ""}, 
    { external_id = ""}
  ]
}
```
AFTER
```
{
  element = "",
  value = [
    { 
	id = "", 
	renditions = [{ id = "" }, { external_id = "" }] 
    }, 
    { 
	codename = "",
	rendition = []
    }, 
    { 
	external_id = ""
	renditions = [{ id = ""}]
    }
  ]
}
```

### Additional context

The feature will be publically released in MAPI ~7.3.2022.
Documentation is not yet public.

**Comment by Suzii** [comment]
@gormal is it necessary to update readme with code samples on how to work with renditions?

**Comment by Suzii** [comment]
PR merged. Leaving the issue open, because Readme needs to be updated with renditions' code samples.

**Comment by Simcsa** [comment]
Readme does not need to be updated with renditions code samples - the docu examples are enough in this case.

But, the code examples from docu need to be added into tests in this SDK. Done here: https://github.com/Kentico/kontent-management-sdk-net/pull/156

**Comment by gormal** [comment]
Done. Thank you all for your contribution!
