### ISSUE TITLE
Add regex validation data to URL slug element model

### ISSUE THREAD

**Issue by Iorethan** [Kentico/kontent-management-sdk-net#143]
### Motivation

Regex validations for URL slug elements are to be added to Kontent. This extends models of URL slug elements with a regex object. This addition should be reflected in the SDK.

### Proposed solution

Extend URL slug model with the same regex object as is used in text elements. The changes should be the same as done it those two PRs that modified text element in the same way:
https://github.com/Kentico/kontent-management-sdk-net/pull/108
https://github.com/Kentico/kontent-management-sdk-net/pull/118

### Additional context

The feature is planned to be released on March 2. Documentation is not public yet, but you can take inspiration from documentation of regex validations for text elements as the regex object is the same: https://kontent.ai/learn/reference/management-api-v2/#section/Text-element-in-type

**Comment by gormal** [comment]
Done in #152
