### ISSUE TITLE
Add support for elements in Asset entity

### ISSUE THREAD

**Issue by Suzii** [Kentico/kontent-management-sdk-net#144]
### Motivation

The feature "asset tagging", internally represented as the presence of Taxonomy elements in the Asset entity was introduced to the UI a while ago and now has made its way to the MAPI as well. Now is the time to add support to MAPI SDKs.

### Proposed solution

Introduce new property `Elements` to the Asset entity and make it work. The idea for the API to be exactly the same as elements in language variants, although Asset currently only supports Taxonomy elements that are non-localizable. The API and SDKs, however, should be "generic" enough so that any type element can be easily supported in the future.

### Additional context

The feature will be released ~7.3.2022. Docs are not public yet.

The `Elements` property is being returned from the GET endpoints and is optionally accepted in the POST/PUT endpoints. Only elements that are present during insert/update/upsert will be modified.

**Comment by Suzii** [comment]
@gormal should I update these parts of readme? https://github.com/Kentico/kontent-management-sdk-net#asset-methods

**Comment by gormal** [comment]
If you have time for it that would be great.

**Comment by Suzii** [comment]
Both code and the code sample PRs merged. Can we close the issue now? :)

**Comment by gormal** [comment]
Sure ;)
