### ISSUE TITLE
Propagate Retry-After header value

### ISSUE THREAD

**Issue by matus12** [Kentico/kontent-management-sdk-net#39]
### Motivation

When I disable the default resilience logic in the `ContentManagementClient` and I exceed the [API rate limit](https://developer.kenticocloud.com/v1/reference#content-management-api-v2-rate-limits), I have no way to find out how long I should wait before retrying the request.
### Proposed solution

I should be able to get the value of the `Retry-After` header in the `ContentManagementException`, e.g., in the [JavaScript Content Management SDK](https://github.com/Kentico/kentico-cloud-js/tree/b39faf662544ae88ddcc698c672be91cf44aa073/packages/content-management), the [original error is included](https://github.com/Kentico/kentico-cloud-js/blob/b39faf662544ae88ddcc698c672be91cf44aa073/packages/content-management/lib/models/shared/shared-models.ts#L34).

**Comment by PetrSvirak** [comment]
It would be a nice touch if the SDK provided an option to retry 429 automatically as well…

**Comment by matus12** [comment]
The SDK actually does have the 429 in the [list of status codes to retry](https://github.com/Kentico/content-management-sdk-net/blob/da61e8d4cd6551fe46e34accdcf5df06885dc588/KenticoCloud.ContentManagement/Modules/ResiliencePolicy/RetryHttpCode.cs#L6) in the default retry policy, however, it doesn't take the `retry-after` value into consideration when to retry the request.

**Comment by PetrSvirak** [comment]
That's actually what I mean; while I'm not sure whether it should be part of default retry policy per se, SDK should IMO be able to handle `retry-after` in the response header (right it is just to some extent). 

While allowing SDK users to reach the value feels like a bare minimum to me, it would be great if they didn't need to upscale retry count to about 10 artificially just to get past CM API rate limiting via default retry policy (that also applies to 429 by default as of now).
