### ISSUE TITLE
Enhance Validation Errors Messages inside the Exceptions when trying to upsert ContentItemVariant

### ISSUE THREAD

**Issue by hugobarona** [Kentico/kontent-management-sdk-net#43]
### Motivation

I noticed during my content migration process that if i have a property that does not accept value of NULL, when i try to upsert the content item variant, it throws an exception with validation errors, but it is not explicit which fields have the problem. So, if i have 20-30 fields with the same problem, it would be beneficial to get information about which fields are failing.

### Proposed solution

Include field names in the validation errors messages

### Additional context

Example of exception as-is:

The provided request body is invalid. See the 'validation_errors' attribute for more information and specify a valid JSON object.
      Validation errors:
      The provided value '<null>' cannot be assigned to an element of type 'RelatedContent'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'Asset'.
      The provided value '<null>' cannot be assigned to an element of type 'Asset'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'MultipleChoice'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'MultipleChoice'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'RelatedContent'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'RelatedContent'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'RelatedContent'.
      The provided value '<null>' cannot be assigned to an element of type 'Asset'.
      The provided value '<null>' cannot be assigned to an element of type 'RelatedContent'.
      The provided value '<null>' cannot be assigned to an element of type 'MultipleChoice'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'RelatedContent'.
      The provided value '<null>' cannot be assigned to an element of type 'RelatedContent'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
      The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
Unhandled exception. KenticoCloud.ContentManagement.Exceptions.ContentManagementException: The provided request body is invalid. See the 'validation_errors' attribute for more information and specify a valid JSON object.

Thank you.

**Comment by petrsvihlik** [comment]
Hi @hugobarona , let me verify it with our devs.


This is what @kentico-michaelb [says](https://app.intercom.io/a/apps/e42kus8l/inbox/inbox/conversation/24736596063):

> I was able to reproduce the issue in a more simple example.  When trying to make a change only to a content item variant that uses a content type consisting of a text element, taxonomy element, and has a linked item element, if I only specify the text element update, I get the exception:
> 
> The provided request body is invalid. See the 'validation_errors' attribute for more information and specify a valid JSON object.
> Validation errors:
> The provided value '<null>' cannot be assigned to an element of type 'Taxonomy'.
> The provided value '<null>' cannot be assigned to an element of type 'RelatedContent'.
> 
> This is in contrast to the line: " "The content elements of the language variant you want to add or update. Omitted elements will remain unchanged." from the SDK's readme: https://github.com/Kentico/kontent-management-sdk-net#2-adding-language-variants
> 
> the code I used to test code is attached.
> 
> So it seems like the CM SDK is literally passing the value "<null>" to the API and it blows up, rather than just ignoring it per the readme.

I created a branch with the scenario (I just basically copied Mike's code): https://github.com/Kentico/kontent-management-sdk-net/tree/GetContentItemVariantUpsertModel

and successfully reproduced the issue.

I think we need to add an extra condition (`&& x.GetValue(variantElements) != null`) to this line:

https://github.com/Kentico/kontent-management-sdk-net/blob/0de92bcc6895d2fbad91075c9d7ad5ff6a660c4c/Kentico.Kontent.Management/Modules/ModelBuilders/ModelProvider.cs#L57

(and adjust the failing tests).

If I'm wrong and this is not the case, we need to adjust the docs and remove this like 
> Omitted elements will remain unchanged.

Can you please confirm @ivanaliptakova , @PeterSkoda , or @sutrkiller ?

**Comment by hugobarona** [comment]
Hi @petrsvihlik. We are actually addressing two issues here. My initial issue was related to the lack of information in the validation errors that can guide the devs to identify quickly what are the fields causing the validation errors. Then the second issue, is actually the partial updates using the SDK, when you do not specify non-nullable fields, such as TaxonomyTermIdentifier. I discussed this issue with @kentico-michaelb and he was able to reproduce it. Anyway, i will let you guys figure out what is the best approach.

**Comment by petrsvihlik** [comment]
@hugobarona thank you, noted! :)

**Comment by petrsvihlik** [comment]
@hugobarona just a short update
1) better validation messages are now being worked on by the dev teams
2) the serialization issue in this SDK will be reviewed by @makma

**Comment by makma** [comment]
Yes, the serialization fix looks good to me, moreover, I think it's appropriate to fix it this way. I've also adjusted tests and sample data in https://github.com/Kentico/kontent-management-sdk-net/pull/44.

Thank you @kentico-michaelb for research and your helpful insights and @hugobarona for pointing our attention to the issue!

**Comment by petrsvihlik** [comment]
hey @hugobarona,
you can download the fixed version of the SDK at: https://www.nuget.org/packages/Kentico.Kontent.Management/2.0.1

regarding the error messages, I expect them to be released in January (max. February)...the dev teams are working on them atm.

**Comment by hugobarona** [comment]
Hi @petrsvihlik, thank you for the update. Then since the team is still working in the issue, this one should remain as open, and not closed, right?

Regards,
HB

**Comment by petrsvihlik** [comment]
The improvement will be done on the API level. There isn't much that we can do in this SDK. 
Once the new error messages get released they should propagate through any SDK basically.
You should be notified about the release through one of the usual product update messages. 
Is that ok?

**Comment by hugobarona** [comment]
Ok sounds good. 
Thank you.
