### ISSUE TITLE
Duplicate Sub Nuget published?

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-management-sdk-net#45]
### Brief bug description

There appears to be a problem with your nuget publish I think.

There is Kentico.Kontent.Management.Helpers published to nuget (latest version 2.0.1) published Dec 10.

Then there is also Kentico.Kontent.Management version 2.0.1 also published to nuget.

Which is the ideal version? They appear to be the same except that the .Helpers version might be .NET Full framework only? BUt hard to tell as they point to the same repo (this one) which appears to be for .NET Core?

A bit confused.

**Comment by petrsvihlik** [comment]
Hey @xantari , thanks for pointing this out!

Kentico.Kontent.Management  -> Management SDK
Kentico.Kontent.Management.Helpers -> A helper library for generating edit URLs (links leading to specific content items in app.kontent.ai)

I tried to make it more clear in the readme: https://github.com/Kentico/kontent-management-sdk-net#kentico-kontent-management-net-sdk
