### ISSUE TITLE
ContentManagementHelpersOptions now appears to be ManagementHelpersOptions

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-management-sdk-net#46]
### Brief bug description

In KenticoCloud.ContentManagement.Helpers the edit link helper use to use ContentManagementHelpersOptions, but in the new Kentico.Kontent.Management.Helpers it is now called ManagementHelpersOptions.

You might want to list that as a breaking change when updating and also update your README.MD in this repo which still lists the ContentManagementHelpersOptions class as being a valid code sample.

**Comment by petrsvihlik** [comment]
Thanks, we missed this occurrence and a few others. All should be fixed in:
fixed in https://github.com/Kentico/kontent-management-sdk-net/commit/a5cf211311cadd07c18ab2a7126e5281b0868f95
