### ISSUE TITLE
Make ManagementClient mockable

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-management-sdk-net#53]
### Motivation

It seems only the concrete implementation exists for ManagementClient. 

### Proposed solution

Add interface so it can be mocked / tested.

**Comment by petrsvihlik** [comment]
thanks for inputs @xantari! we'll consider it for the Management API v2 SDK (#50)

in the meantime, we're open to any pull requests!

**Comment by gormal** [comment]
This was done to the vNext branch.

**Comment by Sevitas** [comment]
Reopening this because cannot properly set up a mock for listing endpoints.

**Comment by gormal** [comment]
Mocking for listing endpoints was fixed in #121. I am closing the issue. Feel free to reopen if any other problem occurs.
