### ISSUE TITLE
Width and Height of Asset model are missing

### ISSUE THREAD

**Issue by alex21cn** [Kentico/kontent-management-sdk-net#54]
### Motivation

Why is this feature required? What problems does it solve?

### Proposed solution

An ideal solution for the above problems.

### Additional context

Add any other context, screenshots, or reference links about the feature request here.

**Comment by petrsvihlik** [comment]
@huluvu21 ?

**Comment by xantari** [comment]
@petrsvihlik This fix is also contained in this PR: https://github.com/Kentico/kontent-management-sdk-net/pull/59

I added the ImageHeight / ImageWidth attributes from the V2 API...

**Comment by petrsvihlik** [comment]
Thanks @xantari !
