### ISSUE TITLE
Where to add the possibility of creating a new-version of a language variant?

### ISSUE THREAD

**Issue by zurcacielos** [Kentico/kontent-management-sdk-net#55]
### Expected result
Having the ability of "Add a new version of a language variant" in API v1 for .NET

This is something available in the API v2
https://docs.kontent.ai/reference/management-api-v2#operation/create-a-new-version-of-a-language-variant

But I don't see it in the API v.1. Unless I'm missing something.

Can somebody give a hint on how to modify the API v1 to allow this? that will save me a lot of analysis time.

**Comment by petrsvihlik** [comment]
@huluvu21 ?

**Comment by gormal** [comment]
Hi, we have [new version of SDK](https://github.com/Kentico/kontent-management-sdk-net/releases/tag/3.0.1) that implements all endpoints of MAPI v2.

Feel free to re-open this issue if you have any additional questions.
