### ISSUE TITLE
ManagementException, NextPage - RequestUriTooLong

### ISSUE THREAD

**Issue by andreqb** [Kentico/kontent-management-sdk-net#58]
### Brief bug description

When trying to page through the ListingResponseModel using NextPage I get an exception the first time of RequestUriTooLong

### Repro steps

```
            if (responseItems.HasNextPage())
            {
                await responseItems.GetNextPage()
            }
```

### Expected behavior

Would expect this to just work it is the base case.  The original call works just fine.

### Test environment

AspNetCore 2.2

### Other Notes

The original call is to _client.ListContentItemsAsync()

The continuation token that is being returned is over 16k characters.

**Comment by gormal** [comment]
Hi, this should be fixed in the newest [pre-release](https://github.com/Kentico/kontent-management-sdk-net/releases/tag/3.0.0-beta4).

Feel free to re-open this issue if you need more info.
