### ISSUE TITLE
Auto init of all model properties

### ISSUE THREAD

**Issue by lukasturek** [Kentico/kontent-management-sdk-net#6]
### Motivation

Currently, the developer must write code to initialize fields of content elements, even though they're supposed to be empty.

```csharp
ArticleModel stronglyTypedElements = new ArticleModel
{
    Title = "On Roasts",
    PostDate = new DateTime(2017, 7, 4),
    Personas = new[] { },
    TeaserImage = new AssetIdentifier[]{ },
    MetadataOgImage = new AssetIdentifier[] { },
    MetadataTwitterImage = new AssetIdentifier[] { }
};
```

### Design guidelines

It would be nice to have a support for an automatic initialization of empty fields, so as a developer I don't have to do it manually. For example, I want to update the content model:

```csharp
ArticleModel stronglyTypedElements = new ArticleModel
{
    Title = "On Roasts",
    PostDate = new DateTime(2017, 7, 4)
};
```

### Reference

* [GetContentItemVariantUpsertModel](https://github.com/Kentico/content-management-sdk-net/blob/master/KenticoCloud.ContentManagement/Modules/ModelBuilders/ModelProvider.cs#L51)

**Comment by yrmartinez** [comment]
@petrsvihlik @JanLenoch  I'd like to help with this enhancement. If it's OK, and since you already groomed, could you give me more details?
Thanks.

**Comment by petrsvihlik** [comment]
Hi @yrmartinez , I sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.

Can you please be more specific about what should we clarify about this issue?

Basically, we need to make sure that the models (two code blocks in the description) get serialized into a JSON with all it's properties.

It may be as easy as changing the [NullValueHandling](https://github.com/Kentico/content-management-sdk-net/blob/master/KenticoCloud.ContentManagement/Modules/ActionInvoker/ActionInvoker.cs#L20) but it can be also a bit more tricky. We need to cover the serialization with unit tests and test the serialized models against the live API.

**Comment by NammoPillai** [comment]
Hi @petrsvihlik, is this something that still needs to be worked on, seeing as this issue was opened in 2018?

**Comment by petrsvihlik** [comment]
Hi, I'm no longer on the team. Tagging the code owners @Kentico/developer-experience

**Comment by makma** [comment]
Hi @NammoPillai, thank you for your interest.
To be honest, I was not sure whether this issue is still valid so I tried it. I was able to upsert a variant with just a subset of the elements of the content item.

I've got an `Article` content type with two elements (`title` and `description`). Both of them are Text elements.
When I tried to upsert variant with just a single element (`title`) specified, the upsert action worked without errors, and the item was also updated in Kontent. I believe this issue might have been fixed during some refactoring or migration to .NET Core but I'm not sure whether is this the exact scenario.
@lukasturek , could you confirm this was the desired scenario?

## My Article model
``` c#
    public partial class Article
    {
        public const string Codename = "article";
        public const string DescriptionCodename = "description";
        public const string TitleCodename = "title";

        public string Description { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
```

## Upsert logic
```c#
        static async System.Threading.Tasks.Task Main(string[] args)
        {
            ManagementOptions options = new ManagementOptions
            {
                ProjectId = "40...",
                ApiKey = "ew..."
            };

            // Initializes an instance of the ManagementClient client
            ManagementClient client = new ManagementClient(options);

            // Elements to update
            Article stronglyTypedElements = new Article
            {
                Title = "On Roasts1"
            };

            // Specifies the content item and the language variant
            ContentItemIdentifier itemIdentifier = ContentItemIdentifier.ByCodename("hello");
            LanguageIdentifier languageIdentifier = LanguageIdentifier.ByCodename("default");
            ContentItemVariantIdentifier identifier = new ContentItemVariantIdentifier(itemIdentifier, languageIdentifier);


            // Upserts a language variant of a content item
            ContentItemVariantModel<Article> response = await client.UpsertContentItemVariantAsync<Article>(identifier, stronglyTypedElements);
        }
```

**Comment by lukasturek** [comment]
@makma This is exactly the desired behavior. I'm not aware of this fix, but glad to hear that it's working now. Closing the issue.
@NammoPillai Thank you for trying to help though, really appreciate it!
