### ISSUE TITLE
Refactor ManagementClientTests Architecture

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-management-sdk-net#69]
### Motivation

* Currently, the tests are hard to maintain, read, and basically dependent on the live project in Kontent if new features are added and bugs are fixed.
* Re-generation requires there steps - Re-run ManagementClientTests with `private static readonly TestUtils.TestRunType _runType = TestUtils.TestRunType.MockFromFileSystem;`, after tests are green, commit changes in `~/Kentico.Kontent.Management.Tests/Data/*`

Come up with a better approach that would test the SDK functionality without necessity to pre-record requests and reposnse.

### Proposed solution

These are just possible enhancements:
* [x] Do now generate hash under `Data` folder - identify mock responses just by test name - so that update does not generate folder removal and addiction - and this pair is hard to distinguish
* [ ] Automate regeneration of the mock files
* [ ] Hardcode the JSONs and avoid auto-generation completely

### Additional context

* We might use [MAPI Swagger definition](https://kcdmaster.blob.core.windows.net/api-reference-specifications/management_api_v2.json) and use it for mock server -  (if URL does not work - reach out to @Simply007)

### Related issues

#79 #66 #64

**Comment by gormal** [comment]
All tests have been re-written in a new way.
