### ISSUE TITLE
id is not assignable to IRichTextComponent 

### ISSUE THREAD

**Issue by kentico-michaelb** [Kentico/kontent-management-sdk-net#74]
### Brief bug description

When using the languageVariantElementsBuilder in v1.3.0 of the SDK, the id property of a component object in a richTextElement throws error:

_Type '{ id: string; type: { codename: string; }; elements: { element: { codename: string; }; value: string; }[]; }' is not assignable to type 'IRichTextComponent'.
  Object literal may only specify known properties, and 'id' does not exist in type 'IRichTextComponent'.ts(2322)_

### Repro steps

1. Open the Kontent Migrations Boilerplate
2. Add the following code to a new TypeScript file in the project:
```await apiClient
.upsertLanguageVariant()
.byItemId(test)
.byLanguageCodename('default')
    .withData((builder) => [
      builder.richTextElement({
          element:{
              codename:"my_test_rte"
          },
          value:'<object type="application/kenticocloud" data-type="component" data-id="382abced-bfb6-4ee9-a2d4-2c3b8cd8ba5d"></object>',
          components: [
              {
                  id: "382abced-bfb6-4ee9-a2d4-2c3b8cd8ba5d",
                  type: {
                      codename:"article",
                  },
                  elements: [
                      {
                          element: {
                              codename: "my_text_element",
                          },
                          value: "Here is the text",
                      },
                  ],
              }
          ]
      })
      ])
      .toPromise()
```
### Expected behavior

No IDE warning and _id_ exists for IRichTextComponent per the M API documentation: https://docs.kontent.ai/reference/management-api-v2#section/Rich-text-element 

### Additional context

Probably should be added here: https://github.com/Kentico/kontent-management-sdk-js/blob/914e022a58adb2c7b4e68980041087c75b459235/lib/models/language-variants/language-variant-elements-builder.ts#L9

**Comment by Simply007** [comment]
Hey @kentico-michaelb,

I guess this issue should be submitted in JS management SDK right?

**Comment by kentico-michaelb** [comment]
*doh*. Yes of course. Too many tabs open and support conversations happening at the same time. Sorry. I'll close it and rewrite it.
