### ISSUE TITLE
Unify naming of Content Item Language variant

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-management-sdk-net#83]
### Motivation

There is currently a clash between `Content ItemVariant and `LanguageVariant` in the solution.

+ Rename `ChangeWorkflowStep` to ChangeContentItemVariantWorkflowStep
 based on internal feedback - https://kentico.atlassian.net/wiki/spaces/KDevRel/pages/2973433892/.NET+Management+SDK

### Proposed solution

The naming should be unified we should call the content item language variant the same in the solution.

‼ **FINAL DECISION** - **LanguageVariant** ‼
* https://docs.kontent.ai/reference/management-api-v2#tag/Language-variants

**Comment by gormal** [comment]
Fixed in #93
